# Generated by Django 4.1.6 on 2023-02-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="user", new_name="ludzie",),
    ]
