# Generated by Django 4.1.7 on 2023-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_date_created_profile_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("mood", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=20)),
            ],
        ),
    ]
