# Generated by Django 4.1.7 on 2023-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_mood"),
    ]

    operations = [
        migrations.RemoveField(model_name="mood", name="mood",),
        migrations.AlterField(
            model_name="mood",
            name="color",
            field=models.CharField(
                choices=[("1", "Green"), ("2", "Yellow"), ("3", "Red")], max_length=1
            ),
        ),
    ]
