# Generated by Django 4.1.7 on 2023-02-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_mood_mood_alter_mood_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="color",
            field=models.CharField(
                choices=[
                    ("R", "Red"),
                    ("O", "Orange"),
                    ("Y", "Yellow"),
                    ("G", "Green"),
                    ("B", "Blue"),
                    ("P", "Purple"),
                ],
                max_length=1,
            ),
        ),
    ]
