# Generated by Django 4.1.7 on 2023-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_mood_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
