# Generated by Django 4.1.7 on 2023-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_day_entry_news_delete_mood"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                            ("anxious", "Anxious"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
