# Generated by Django 4.1.7 on 2023-03-24 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_mood"),
    ]

    operations = [
        migrations.RemoveField(model_name="mood", name="date",),
        migrations.RemoveField(model_name="mood", name="mood",),
        migrations.AddField(
            model_name="mood",
            name="anger",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="anxiety",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mood",
            name="energy",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="happiness",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="motivation",
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
