# Generated by Django 4.1.7 on 2023-06-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0014_use_autofields_for_pk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "happiness",
                    models.IntegerField(
                        choices=[
                            (1, "Very unhappy"),
                            (2, "Unhappy"),
                            (3, "Slightly unhappy"),
                            (4, "Neutral"),
                            (5, "Slightly happy"),
                            (6, "Happy"),
                            (7, "Very happy"),
                            (8, "Extremely happy"),
                            (9, "Over the moon"),
                            (10, "Ecstatic"),
                        ]
                    ),
                ),
                (
                    "anger",
                    models.IntegerField(
                        choices=[
                            (1, "Calm"),
                            (2, "Irritated"),
                            (3, "Annoyed"),
                            (4, "Frustrated"),
                            (5, "Angry"),
                            (6, "Enraged"),
                            (7, "Fuming"),
                            (8, "Livid"),
                            (9, "Seething"),
                            (10, "Raging"),
                        ]
                    ),
                ),
                (
                    "anxiety",
                    models.IntegerField(
                        choices=[
                            (1, "Calm"),
                            (2, "Uneasy"),
                            (3, "Nervous"),
                            (4, "Apprehensive"),
                            (5, "Anxious"),
                            (6, "Panicky"),
                            (7, "Distressed"),
                            (8, "Terrified"),
                            (9, "Paralyzed"),
                            (10, "Overwhelmed"),
                        ]
                    ),
                ),
                (
                    "energy",
                    models.IntegerField(
                        choices=[
                            (1, "Exhausted"),
                            (2, "Sleepy"),
                            (3, "Tired"),
                            (4, "Fatigued"),
                            (5, "Neutral"),
                            (6, "Energetic"),
                            (7, "Excited"),
                            (8, "Hyperactive"),
                            (9, "Manic"),
                            (10, "Unstoppable"),
                        ]
                    ),
                ),
                (
                    "motivation",
                    models.IntegerField(
                        choices=[
                            (1, "Demotivated"),
                            (2, "Apathetic"),
                            (3, "Uninterested"),
                            (4, "Bored"),
                            (5, "Neutral"),
                            (6, "Interested"),
                            (7, "Motivated"),
                            (8, "Inspired"),
                            (9, "Passionate"),
                            (10, "Obsessed"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, default="profile2.png", null=True, upload_to=""
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mood", models.CharField(max_length=50)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schedule.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
