# Generated by Django 4.1.7 on 2023-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood_tracker", "0002_remove_moodentry_user_mood_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="happiness",
            field=models.IntegerField(
                choices=[
                    (0, "Happiness level"),
                    (1, "Very unhappy"),
                    (2, "Unhappy"),
                    (3, "Neutral"),
                    (4, "Happy"),
                    (5, "Very happy"),
                    (6, "Over the moon"),
                ]
            ),
        ),
    ]
