# Generated by Django 4.1.7 on 2023-06-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood_tracker", "0003_alter_mood_happiness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="anger",
            field=models.IntegerField(
                choices=[
                    (0, "Anger level"),
                    (1, "Calm"),
                    (2, "Irritated"),
                    (3, "Annoyed"),
                    (4, "Frustrated"),
                    (5, "Angry"),
                    (6, "Fuming"),
                    (7, "Raging"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="anxiety",
            field=models.IntegerField(
                choices=[
                    (0, "Anxiety level"),
                    (1, "Calm"),
                    (2, "Uneasy"),
                    (3, "Nervous"),
                    (4, "Anxious"),
                    (5, "Distressed"),
                    (6, "Terrified"),
                    (7, "Overwhelmed"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="energy",
            field=models.IntegerField(
                choices=[
                    (0, "Energy level"),
                    (1, "Exhausted"),
                    (2, "Tired"),
                    (3, "Neutral"),
                    (4, "Energetic"),
                    (5, "Excited"),
                    (6, "Hyperactive"),
                    (7, "Manic"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="happiness",
            field=models.IntegerField(
                choices=[
                    (0, "Happiness level"),
                    (1, "Very unhappy"),
                    (2, "Unhappy"),
                    (3, "Neutral"),
                    (4, "Happy"),
                    (5, "Very happy"),
                    (6, "Over the moon"),
                    (7, "Ecstatic"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="motivation",
            field=models.IntegerField(
                choices=[
                    (0, "Motivation level"),
                    (1, "Demotivated"),
                    (2, "Apathetic"),
                    (3, "Bored"),
                    (4, "Neutral"),
                    (5, "Motivated"),
                    (6, "Inspired"),
                    (7, "Obsessed"),
                ]
            ),
        ),
    ]
