# Generated by Django 3.2.19 on 2023-06-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0004_alter_mood_anger_alter_mood_anxiety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='descriptionn',
            field=models.CharField(default='Hello world', max_length=200),
        ),
    ]
