# Generated by Django 4.1.7 on 2023-07-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood_tracker", "0006_rename_descriptionn_mood_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="static/images/profile2.png",
                null=True,
                upload_to="",
            ),
        ),
    ]
