# Generated by Django 4.1.7 on 2023-07-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood_tracker", "0007_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="profile2.png", null=True, upload_to=""
            ),
        ),
    ]
