# Generated by Django 3.2.19 on 2023-07-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='happiness',
            field=models.IntegerField(choices=[(1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
    ]
