# Generated by Django 3.2.19 on 2023-07-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0009_alter_mood_happiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='anger',
            field=models.IntegerField(choices=[(0, 'How angry are you?'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
        migrations.AlterField(
            model_name='mood',
            name='anxiety',
            field=models.IntegerField(choices=[(0, 'How anxious are you?'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
        migrations.AlterField(
            model_name='mood',
            name='energy',
            field=models.IntegerField(choices=[(0, 'How energized are you?'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
        migrations.AlterField(
            model_name='mood',
            name='happiness',
            field=models.IntegerField(choices=[(0, 'How happy are you?'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
        migrations.AlterField(
            model_name='mood',
            name='motivation',
            field=models.IntegerField(choices=[(0, 'How motivated are you?'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
    ]
