# Generated by Django 3.2.19 on 2023-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0010_auto_20230708_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='anger',
            field=models.IntegerField(choices=[(0, 'Anger'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
        migrations.AlterField(
            model_name='mood',
            name='anxiety',
            field=models.IntegerField(choices=[(0, 'Anxiety'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
        migrations.AlterField(
            model_name='mood',
            name='energy',
            field=models.IntegerField(choices=[(0, 'Energy'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
        migrations.AlterField(
            model_name='mood',
            name='happiness',
            field=models.IntegerField(choices=[(0, 'Happiness'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
        migrations.AlterField(
            model_name='mood',
            name='motivation',
            field=models.IntegerField(choices=[(0, 'Motivation'), (1, 'Very low'), (2, 'Low'), (3, 'Moderate'), (4, 'Medium'), (5, 'High'), (6, 'Very high'), (7, 'Extreme')]),
        ),
    ]
