# Generated by Django 3.2.19 on 2023-07-16 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0013_auto_20230716_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='task_id',
        ),
        migrations.AddField(
            model_name='reminder1',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder1',
            name='task_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
