# Generated by Django 3.2.19 on 2023-07-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0014_auto_20230716_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder1',
        ),
    ]
