# Generated by Django 3.2.19 on 2023-07-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0016_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('dose', models.IntegerField()),
                ('dose_time', models.DateTimeField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedsReminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood_tracker.medicine')),
            ],
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.AddField(
            model_name='medicine',
            name='reminders',
            field=models.ManyToManyField(to='mood_tracker.MedsReminders'),
        ),
    ]
