# Generated by Django 3.2.19 on 2023-07-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0017_auto_20230718_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
