# Generated by Django 3.2.19 on 2023-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0018_alter_medicine_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
