# Generated by Django 3.2.19 on 2023-07-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0019_alter_medicine_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='dose_time',
        ),
    ]
