# Generated by Django 3.2.19 on 2023-07-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0021_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
