# Generated by Django 3.2.19 on 2023-07-19 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0023_dailyroutine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyroutine',
            old_name='task',
            new_name='title',
        ),
        migrations.AddField(
            model_name='dailyroutine',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
