# Generated by Django 3.2.19 on 2023-08-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0025_auto_20230803_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyroutine',
            name='user',
        ),
    ]
