# Generated by Django 3.2.19 on 2023-08-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0027_dailyroutine_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyroutine',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.CreateModel(
            name='MedsReminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood_tracker.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='reminders',
            field=models.ManyToManyField(to='mood_tracker.MedsReminders'),
        ),
    ]
